### ISSUE TITLE
wc.seach接口报错

### ISSUE THREAD

**Issue by shitongbin** [GraySilver/wencai-master#22]
wc.search接口报错，好像用不了了：
`Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen       
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connection.py", line 505, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\Anaconda3\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\Administrator\Anaconda3\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Users\Administrator\Anaconda3\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='search.10jqka.com.cn', port=443): Max retries exceeded with url: /unifiedwap/unified-wap/v2/result/get-robot-data (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\wencai\core\event.py", line 48, in search
    return Wencai(proxies=globals()['global_proxies'], verify=globals()['verify']).search(query_string=query)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\wencai\core\crawler.py", line 101, in search
    data=payload, force_cookies=True)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\wencai\core\session.py", line 51, in post_result
    return super(Session, self).post(url=url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 274, in resolve_redirects
    **adapter_kwargs,
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='search.10jqka.com.cn', port=443): Max retries exceeded with url: /unifiedwap/unified-wap/v2/result/get-robot-data (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))`

**Comment by logsave** [comment]
我提交修复了,现在还没合入master. https://github.com/logsave/wencai.git

**Comment by qingyuan0o0** [comment]
从2022年11月11日我最后使用过后，不知道时哪天开始，这个接口需要登录才可以用了。如果不限制调用频率的爬，会导致服务器资源被吃满崩溃的，

**Comment by liuzhijian** [comment]
> 

请问下登录是要怎么操作登录？不太理解他里面的cookies机制，我想拿一个pro的账号来试试，搜索条件长度限制了
