### ISSUE TITLE
connection or something of lack

### ISSUE THREAD

**Issue by matrixloong** [GraySilver/wencai-master#26]
D:\.virtualenvs\study\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'search.10jqka.com.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "d:\sourcecodes\projects\seekentries.py", line 3, in <module>
    result = wc.search(query="当前热股")
  File "D:\.virtualenvs\study\lib\site-packages\wencai\core\event.py", line 48, in search
    return Wencai(proxies=globals()['global_proxies'], verify=globals()['verify']).search(query_string=query)
  File "D:\.virtualenvs\study\lib\site-packages\wencai\core\crawler.py", line 102, in search
    result = r.json()['data']['answer'][0]['txt'][0]['content']['components'][0]['data']['datas']
TypeError: list indices must be integers or slices, not str

**Comment by uuhasoo** [comment]
import wencai as wc
from wencai.core.session import Session
Session.headers.update({'Host':'www.iwencai.com'})
wc.set_variable(cn_col=True)
wc.search('人气股票').head(10)

**Comment by matrixloong** [comment]
thanks a lot, uuhasoo

> import wencai as wc from wencai.core.session import Session Session.headers.update({'Host':'www.iwencai.com'}) wc.set_variable(cn_col=True) wc.search('人气股票').head(10)

**Comment by TaucherLoong** [comment]
How to login as a user? non user can't use the web after some seek limits.

**Comment by matrixloong** [comment]
that is my problem now, so i want to login as a user



| |
matrixloong
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 02/07/2023 13:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [GraySilver/wencai] connection or something of lack (Issue #26) |

How to login as a user? non user can't use the web after some seek limits.

**Comment by liuzhijian** [comment]
> How to login as a user? non user can't use the web after some seek limits.

我也是
