### ISSUE TITLE
ws.search不能用了吗? requests.exceptions.JSONDecodeError

### ISSUE THREAD

**Issue by Vincent1893** [GraySilver/wencai-master#30]
Traceback (most recent call last):
  File "D:\develope\IdeaProjects\PythonHelloword\.idea\src\WenCaiAPI.py", line 192, in <module>
    str =wc.search('今日热股')
  File "D:\develope\IdeaProjects\python3.9_space\lib\site-packages\wencai\core\event.py", line 48, in search
    return Wencai(proxies=globals()['global_proxies'], verify=globals()['verify']).search(query_string=query)
  File "D:\develope\IdeaProjects\python3.9_space\lib\site-packages\wencai\core\crawler.py", line 102, in search
    result = r.json()['data']['answer'][0]['txt'][0]['content']['components'][0]['data']['datas']
  File "D:\develope\IdeaProjects\python3.9_space\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

这个是被反爬限制了吗？

**Comment by Vincent1893** [comment]
貌似是偶发性问题   似乎是频繁调用后会出现这种错误
